#' Import bio-kine ascii files (.bka)
#'
#' This function allows you to import bio-kine ascii files (.bka). 
#' These are the standard output of BioLogic stopped flow devices.
#' @importFrom magrittr %>%
#' @param path Path to the input .bka file
#' @export
#' @examples
#' read_biokine(path = "my_file.bka")

read_biokine <- function(path = ""){
  comment_lines <- readr::read_lines(path, n_max = 100) %>%
    stringr::str_detect("\"")
  
  comment_lines <- max(which(comment_lines))
  
  data <- readr::read_tsv(file = path, skip = comment_lines, col_names = c("time", "value"), col_types = readr::cols(time = readr::col_double(), value = readr::col_double()))
  
  return(data)
}






#' Import all bio-kine ascii files (.bka) in a directory
#'
#' This function allows you to import multiple bio-kine ascii files (.bka) in a directory. 
#' These are the standard output of BioLogic stopped flow devices.
#' @importFrom magrittr %>%
#' @param path Path to the input directory containing the .bka files to read
#' @export
#' @examples
#' read_biokine_all(path = "my_dir")

read_biokine_all <- function(path = "."){
  files <- list.files(path, pattern = ".bka$", full.names = T, recursive = T)
  
  data_list <- lapply(files, read_biokine)
  
  names(data_list) <- list.files(path, pattern = ".bka$", recursive = T)
  
  data <- tibble::enframe(data_list) %>%
    tidyr::unnest(value)
  
  return(data)
}





#' Calculate moving average
#'
#' This function calculates a moving average of a vector for smoothing data 
#' (e.g. time series).
#' @importFrom magrittr %>%
#' @param x Vector for which to calculate moving average
#' @param window Width of the window for the moving average. Number of 
#' neighboring values that will be averaged at each position of x.
#' @export
#' @examples
#' moving_av(x = rnorm(100), window = 5)

moving_av <- function(x, window = 5){
  stats::filter(x, rep(1 / window, window), sides = 2)
}


#' Reduce number of time points by averaging values of multiple time points
#'
#' This function reduces the number of time points in a data frame by averaging 
#' values from multiple time points.
#' @importFrom magrittr %>%
#' @param data A data frame with two columns: time and value
#' @param width Number of time/value pairs that will be averaged into one pair
#' @export
#' @examples
#' timeseries_av(data = tibble(time = 1:100, value = rnorm(100)), window = 5)

timeseries_av <- function(data, window = 5){
  rows <- floor(nrow(data)/window)*window
  data <- data[1:rows,]
  
  var_1 <- colnames(data)[1]
  var_2 <- colnames(data)[2]
  
  data$grouping_column_ts <- rep(1:floor(nrow(data)/window), each = window)
  
  data <- data %>%
    dplyr::group_by(grouping_column_ts) %>%
    dplyr::summarise({{var_1}} := mean(.data[[var_1]]),
                     {{var_2}} := mean(.data[[var_2]])) %>%
    dplyr::select(-grouping_column_ts)
  
  return(data)
}





#' Monte Carlo simulations of linear least squares models
#'
#' Perform Monte Carlo (MC) simulations of non linear least squares models.
#' @importFrom magrittr %>%
#' @param model A nls object to perform MC calculations with
#' @param runs Number of MC runs to perform (defaults to 1000)
#' @export
#' @examples
#' n <- nls(mpg ~ k * e ^ wt, data = mtcars, start = list(k = 1, e = 2))
#' nls_MC(n)



nls_MC <- function(model, runs = 1000){
  
  sigma     <- broom::glance(model)$sigma
  start     <- summary(model)$param[,1]
  params_MC <- tibble::tibble()
  data      <- broom::augment(model)
  var       <- model$m$formula() %>% as.character() %>% .[2]
  opt       <- model$control
  opt$warnOnly <- FALSE
  
  for(i in 1:runs){
    data_MC <- data
    data_MC[var] <- data$.fitted + rnorm(n = nrow(data), mean = 0, sd = sigma)
    try <- try(
      nls <- nls(model$m$formula(),
                 data    = data_MC, 
                 start   = start, 
                 control = opt),
      silent = T
    )
    if(!"try-error" %in% class(try)){
      params_MC <- dplyr::bind_rows(params_MC, broom::tidy(try) %>% tibble::add_column(run = i))
    }
  }
  return(params_MC)
}






#' Summarize Monte Carlo simulations of linear least squares models
#'
#' Summarizes the output of the nls_MC() function. For each fitted parameter 
#' mean, median, standard deviation and confidence intervals are computed.
#' @importFrom magrittr %>%
#' @param data A tibble generated by nls_MC()
#' @param conf.level Level for confidence interval calculation (defaults to 0.95)
#' @export
#' @examples
#' n <- nls(mpg ~ k * e ^ wt, data = mtcars, start = list(k = 1, e = 2))
#' s <- nls_MC(n)
#' summarise_nls_MC(s, conf.level = 0.99)



summarise_nls_MC <- function(data, conf.level = 0.95){
  
  lo <- (1-conf.level)/2
  hi <- 1-(1-conf.level)/2
  
  return(
    data %>%
      dplyr::group_by(term) %>%
      dplyr::summarise(
        estimate_mean   = mean(estimate),
        estimate_median = median(estimate),
        estimate_sd     = sd(estimate),
        CI_lo = quantile(estimate, lo),
        CI_hi = quantile(estimate, hi))
  )
}







